-- Algarve Monitor: seed de entidades. verificado=0 ate validacao.

CREATE TABLE IF NOT EXISTS entidades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL CHECK (tipo IN (
        'camara_municipal','agencia_publica','associacao','incubadora',
        'universidade','media_local','media_nacional','fonte_dados','fonte_eventos')),
    ambito TEXT CHECK (ambito IN ('municipal','regional','nacional','internacional')),
    municipio TEXT,
    website TEXT,
    metodo_acesso TEXT CHECK (metodo_acesso IN ('rss','api','scrape','manual','email')),
    url_recolha TEXT,
    camadas TEXT,            -- csv: noticias,eventos,financiamento,empresas,turismo,voos,investigacao,economia
    prioridade INTEGER DEFAULT 2,  -- 1 alta (v1), 2 media, 3 baixa (fases seguintes)
    verificado INTEGER DEFAULT 0,  -- 0 ate o check de feeds/APIs correr
    activo INTEGER DEFAULT 1,
    ultima_verificacao TEXT,
    notas TEXT
);

INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Albufeira','camara_municipal','municipal','Albufeira','https://www.cm-albufeira.pt','rss','https://www.cm-albufeira.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Alcoutim','camara_municipal','municipal','Alcoutim','https://www.cm-alcoutim.pt','rss','https://www.cm-alcoutim.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Aljezur','camara_municipal','municipal','Aljezur','https://www.cm-aljezur.pt','rss','https://www.cm-aljezur.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Castro Marim','camara_municipal','municipal','Castro Marim','https://www.cm-castromarim.pt','rss','https://www.cm-castromarim.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Faro','camara_municipal','municipal','Faro','https://www.cm-faro.pt','rss','https://www.cm-faro.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Lagoa','camara_municipal','municipal','Lagoa','https://www.cm-lagoa.pt','rss','https://www.cm-lagoa.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Lagos','camara_municipal','municipal','Lagos','https://www.cm-lagos.pt','rss','https://www.cm-lagos.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Loulé','camara_municipal','municipal','Loulé','https://www.cm-loule.pt','rss','https://www.cm-loule.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Monchique','camara_municipal','municipal','Monchique','https://www.cm-monchique.pt','rss','https://www.cm-monchique.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Olhão','camara_municipal','municipal','Olhão','https://www.cm-olhao.pt','rss','https://www.cm-olhao.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Portimão','camara_municipal','municipal','Portimão','https://www.cm-portimao.pt','rss','https://www.cm-portimao.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de São Brás de Alportel','camara_municipal','municipal','São Brás de Alportel','https://www.cm-sbras.pt','rss','https://www.cm-sbras.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Silves','camara_municipal','municipal','Silves','https://www.cm-silves.pt','rss','https://www.cm-silves.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Tavira','camara_municipal','municipal','Tavira','https://www.cm-tavira.pt','rss','https://www.cm-tavira.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Vila do Bispo','camara_municipal','municipal','Vila do Bispo','https://www.cm-viladobispo.pt','rss','https://www.cm-viladobispo.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Câmara Municipal de Vila Real de Santo António','camara_municipal','municipal','Vila Real de Santo António','https://www.cm-vrsa.pt','rss','https://www.cm-vrsa.pt/feed','noticias,eventos',2,'Testar /feed e pagina de noticias; muitas camaras nao tem RSS e passam a scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('CCDR Algarve','agencia_publica','regional',NULL,'https://www.ccdr-alg.pt','rss','https://www.ccdr-alg.pt/feed','noticias,financiamento',1,'Fundos regionais, avisos PT2030, noticias institucionais');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('AMAL - Comunidade Intermunicipal do Algarve','agencia_publica','regional',NULL,'https://www.amal.pt','scrape',NULL,'noticias',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Turismo do Algarve (RTA)','agencia_publica','regional',NULL,'https://www.turismodoalgarve.pt','scrape',NULL,'noticias,turismo,eventos',1,'Inclui Observatorio de Turismo Sustentavel (relatorios anuais)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Universidade do Algarve','universidade','regional','Faro','https://www.ualg.pt','rss','https://www.ualg.pt/rss','noticias,eventos,investigacao',1,'Noticias e agenda; producao cientifica via OpenAlex, nao daqui');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('CRIA - Divisão de Empreendedorismo e Transferência de Tecnologia (UAlg)','incubadora','regional','Faro','https://www.ualg.pt/cria','scrape',NULL,'noticias,empresas',1,'Spinoffs e projectos incubados alimentam o directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('DRAP Algarve','agencia_publica','regional',NULL,'https://www.drapalgarve.gov.pt','scrape',NULL,'noticias',3,'Agroalimentar; prioridade baixa no v1');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Algarve Evolution','associacao','regional','Faro','https://algarveevolution.pt','manual',NULL,'noticias,eventos,empresas',1,'Fonte interna: agenda propria, rede de startups, ATH Summit');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Algarve Tech Hub','associacao','regional',NULL,'https://algarvetechhub.com','scrape',NULL,'noticias,eventos,empresas',1,'Confirmar estado actual do site');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Algarve STP - Science and Technology Park','incubadora','regional','Loulé','https://algarvestp.pt','scrape',NULL,'noticias,empresas',1,'Confirmar dominio e estado; historicamente ligado a UAlg/Loule');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('NERA - Associação Empresarial da Região do Algarve','associacao','regional','Loulé','https://www.nera.pt','rss','https://www.nera.pt/feed','noticias,eventos',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('ACRAL - Associação do Comércio e Serviços da Região do Algarve','associacao','regional','Faro','https://www.acral.pt','scrape',NULL,'noticias',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('AHETA - Associação dos Hotéis e Empreendimentos Turísticos do Algarve','associacao','regional',NULL,'https://www.aheta.pt','scrape',NULL,'noticias,turismo',2,'Barometros mensais de ocupacao hoteleira');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('AIHSA - Associação dos Industriais Hoteleiros e Similares do Algarve','associacao','regional',NULL,NULL,'manual',NULL,'noticias,turismo',3,'Confirmar presenca online');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('ANJE - Núcleo do Algarve','associacao','regional','Faro','https://anje.pt','rss','https://anje.pt/feed','noticias,eventos',2,'VERIFICADO 2026-08-04: Rua Mouzinho de Albuquerque 5-A, Faro; anjealgarve@anje.pt; site nacional, filtrar por Algarve; Facebook local sem recolha automatica');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Centro de Incubação e Aceleração de Faro (ANJE)','incubadora','municipal','Faro','https://anje.pt/linc/faro/','manual',NULL,'empresas,eventos',1,'VERIFICADO 2026-08-04: incubadora do nucleo Algarve da ANJE, baixa de Faro; empresas incubadas alimentam o directorio via levantamento manual');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('ABC - Algarve Biomedical Center','associacao','regional','Faro/Loulé','https://abcmedical.pt','scrape',NULL,'noticias,investigacao',2,'Confirmar dominio; inclui ABC CoLAB');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Startup Portimão','incubadora','municipal','Portimão',NULL,'manual',NULL,'noticias,empresas,eventos',2,'Confirmar nome oficial e estado da incubadora municipal');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Incubadoras municipais (levantamento)','incubadora','regional',NULL,NULL,'manual',NULL,'empresas',2,'Levantar via Rede Nacional de Incubadoras: Loule, Lagos, Tavira, VRSA, etc.');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Sul Informação','media_local','regional',NULL,'https://www.sulinformacao.pt','rss','https://www.sulinformacao.pt/feed','noticias',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Barlavento','media_local','regional',NULL,'https://barlavento.sapo.pt','rss','https://barlavento.sapo.pt/feed','noticias',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Postal do Algarve','media_local','regional',NULL,'https://postal.pt','rss','https://postal.pt/feed','noticias',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Jornal do Algarve','media_local','regional',NULL,'https://jornaldoalgarve.pt','rss','https://jornaldoalgarve.pt/feed','noticias',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Região Sul','media_local','regional',NULL,'https://regiao-sul.pt','rss','https://regiao-sul.pt/feed','noticias',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Mais Algarve','media_local','regional',NULL,'https://www.maisalgarve.pt','rss','https://www.maisalgarve.pt/feed','noticias',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Algarve Primeiro','media_local','regional',NULL,'https://www.algarveprimeiro.com','scrape',NULL,'noticias',2,'Sem RSS aparente; scrape');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Algarve Daily News','media_local','regional',NULL,'https://algarvedailynews.com','rss','https://algarvedailynews.com/feed','noticias',2,'Em ingles; util para comunidade estrangeira');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Portugal Resident','media_local','regional',NULL,'https://www.portugalresident.com','rss','https://www.portugalresident.com/feed','noticias',2,'Em ingles; seccao Algarve');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Público','media_nacional','nacional',NULL,'https://www.publico.pt','rss','https://feeds.feedburner.com/PublicoRSS','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Expresso','media_nacional','nacional',NULL,'https://expresso.pt','rss','https://expresso.pt/rss','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('ECO','media_nacional','nacional',NULL,'https://eco.sapo.pt','rss','https://eco.sapo.pt/feed','noticias',1,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Jornal de Negócios','media_nacional','nacional',NULL,'https://www.jornaldenegocios.pt','rss','https://www.jornaldenegocios.pt/rss','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Observador','media_nacional','nacional',NULL,'https://observador.pt','rss','https://observador.pt/feed','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Dinheiro Vivo','media_nacional','nacional',NULL,'https://www.dinheirovivo.pt','rss','https://www.dinheirovivo.pt/rss','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('SAPO Tek','media_nacional','nacional',NULL,'https://tek.sapo.pt','rss','https://tek.sapo.pt/rss','noticias',1,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Exame Informática','media_nacional','nacional',NULL,'https://visao.pt/exameinformatica','scrape',NULL,'noticias',3,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Jornal Económico','media_nacional','nacional',NULL,'https://jornaleconomico.pt','rss','https://jornaleconomico.pt/feed','noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Startup Portugal','media_nacional','nacional',NULL,'https://startupportugal.com','scrape',NULL,'noticias',2,'Filtrar por ''Algarve'' + concelhos + entidades do directorio');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('INE - Instituto Nacional de Estatística','fonte_dados','nacional',NULL,'https://www.ine.pt','api','https://www.ine.pt/ine/json_indicador/pindica.jsp','empresas,turismo,economia',1,'API JSON por indicador; dormidas, constituicoes, desemprego, licencas por concelho');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('PORDATA','fonte_dados','nacional',NULL,'https://www.pordata.pt','manual',NULL,'economia',3,'Backup do INE; sem API estavel');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('dados.gov.pt','fonte_dados','nacional',NULL,'https://dados.gov.pt','api','https://dados.gov.pt/api/1/','empresas,turismo,economia',2,'Inclui dataset RNAL (alojamento local) e Empresa Online');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('IEFP - estatísticas mensais de desemprego','fonte_dados','nacional',NULL,'https://www.iefp.pt/estatisticas','scrape',NULL,'economia',1,'Desemprego registado por concelho, mensal, ficheiros Excel');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('BASE.gov.pt - contratos públicos','fonte_dados','nacional',NULL,'https://www.base.gov.pt','api','https://www.base.gov.pt/Base4/pt/resultados/','financiamento',2,'Contratos tech de entidades algarvias');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('PT2030 - lista de operações aprovadas','fonte_dados','nacional',NULL,'https://portugal2030.pt','scrape',NULL,'financiamento',1,'Beneficiario + concelho + montante; publicacao periodica em CSV/Excel');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('PRR - Recuperar Portugal (beneficiários)','fonte_dados','nacional',NULL,'https://recuperarportugal.gov.pt','scrape',NULL,'financiamento',1,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('CORDIS - Horizon Europe','fonte_dados','internacional',NULL,'https://cordis.europa.eu','api','https://cordis.europa.eu/datalab/','financiamento,investigacao',1,'Filtrar organizacoes com morada no Algarve');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('OpenAlex','fonte_dados','internacional',NULL,'https://openalex.org','api','https://api.openalex.org/works?filter=institutions.ror:','investigacao',2,'Producao cientifica UAlg e afiliadas; obter ROR id da UAlg');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('EPO OPS - patentes','fonte_dados','internacional',NULL,'https://www.epo.org','api','https://ops.epo.org','investigacao',3,'Registo gratuito; volume baixo, cadencia trimestral');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('OpenSky Network - voos Faro (LPFR)','fonte_dados','internacional',NULL,'https://opensky-network.org','api','https://opensky-network.org/api/flights/arrival?airport=LPFR','voos',1,'Chegadas/partidas diarias; passageiros mensais via ANA/INE');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Racius - observatório de empresas','fonte_dados','nacional',NULL,'https://www.racius.com/observatorio/','scrape',NULL,'empresas',1,'Constituicoes e dissolucoes por distrito/concelho; scrape leve com cache');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('TravelBI - Turismo de Portugal','fonte_dados','nacional',NULL,'https://travelbi.turismodeportugal.pt','scrape',NULL,'turismo',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('BPstat - Banco de Portugal','fonte_dados','nacional',NULL,'https://bpstat.bportugal.pt','api','https://bpstat.bportugal.pt/data/v1/','economia',3,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Eurostat','fonte_dados','internacional',NULL,'https://ec.europa.eu/eurostat','api','https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/','economia',3,'NUTS2 Algarve para comparacoes europeias');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Google News: Algarve startup','media_nacional','nacional',NULL,'https://news.google.com','rss','https://news.google.com/rss/search?q=Algarve+startup&hl=pt-PT&gl=PT&ceid=PT:pt','noticias',1,'Rede de seguranca; links sao redirects (resolver URL final antes de dedupe)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Google News: Algarve inovação','media_nacional','nacional',NULL,'https://news.google.com','rss','https://news.google.com/rss/search?q=Algarve+inova%C3%A7%C3%A3o&hl=pt-PT&gl=PT&ceid=PT:pt','noticias',1,'Rede de seguranca; links sao redirects (resolver URL final antes de dedupe)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Google News: Algarve investimento OR financiamento','media_nacional','nacional',NULL,'https://news.google.com','rss','https://news.google.com/rss/search?q=Algarve+(investimento+OR+financiamento)&hl=pt-PT&gl=PT&ceid=PT:pt','noticias',1,'Rede de seguranca; links sao redirects (resolver URL final antes de dedupe)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Google News: Algarve tecnologia','media_nacional','nacional',NULL,'https://news.google.com','rss','https://news.google.com/rss/search?q=Algarve+tecnologia&hl=pt-PT&gl=PT&ceid=PT:pt','noticias',1,'Rede de seguranca; links sao redirects (resolver URL final antes de dedupe)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Google News: Algarve turismo negócios','media_nacional','nacional',NULL,'https://news.google.com','rss','https://news.google.com/rss/search?q=Algarve+turismo+neg%C3%B3cios&hl=pt-PT&gl=PT&ceid=PT:pt','noticias',1,'Rede de seguranca; links sao redirects (resolver URL final antes de dedupe)');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('LinkedIn (curadoria manual via label Gmail)','fonte_eventos','internacional',NULL,'https://www.linkedin.com','email',NULL,'noticias,empresas,eventos',1,'Sem API de pesquisa; partilhar posts por email para label Gmail ''algarve-monitor'', ingestao via gmail_ingest.py (padrao FirstWord); nao usar scrapers com a conta pessoal');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Eventbrite (pesquisa Algarve)','fonte_eventos','internacional',NULL,'https://www.eventbrite.pt','api',NULL,'eventos',2,'API exige token; alternativa scrape da pesquisa por localizacao');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Meetup (grupos Algarve)','fonte_eventos','internacional',NULL,'https://www.meetup.com','scrape',NULL,'eventos',3,'API paga desde 2023; scrape dos grupos conhecidos');
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('Agenda UAlg','fonte_eventos','regional','Faro','https://www.ualg.pt/agenda','scrape',NULL,'eventos',2,NULL);
INSERT INTO entidades (nome,tipo,ambito,municipio,website,metodo_acesso,url_recolha,camadas,prioridade,notas) VALUES ('ATH Summit','fonte_eventos','regional',NULL,NULL,'manual',NULL,'eventos',1,'Confirmar dominio do site do summit');
